// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4692.BELL.subsystems;

import org.usfirst.frc4692.BELL.RobotMap;
import org.usfirst.frc4692.BELL.commands.*;
import edu.wpi.first.wpilibj.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shoot extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon cANTalon1 = RobotMap.shootCANTalon1;
    private final CANTalon cANTalon2 = RobotMap.shootCANTalon2;
    private final CANTalon cANTalon3 = RobotMap.shootCANTalon3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

public void reload() {
	cANTalon1.set(-0.8);
	cANTalon2.set(-0.8);
	cANTalon3.set(0.8);
}

public void fire() {
	cANTalon1.set(.80);
	cANTalon2.set(.80);
	cANTalon3.set(-0.80);
	// TODO Auto-generated method stub

}

public void stop() {
	cANTalon1.set(0);
	cANTalon2.set(0);
	cANTalon3.set(0);
}
public void Finger() {
	cANTalon2.set(1);
}
public void Stop2(){
	cANTalon2.set(0);
}
	// TODO Auto-generated method stub


}


