// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4692.BELL.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc4692.BELL.Robot;

/**
 *
 */
public class AutonomousCommand extends Command {
	double speed;
	Timer BOB=new Timer();

	public  AutonomousCommand(double Speed) {
		// Due to class scope issues, we need to create a field in the base
		// class, and copy any parameters to it for the Execute to access them.
		speed = speed;
	}

  
 

	// Called just before this Command runs the first time
    protected void initialize() {
    	BOB.start();
    	
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.driveSystem.driveStraight(speed);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (BOB.get()>5);
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveSystem.driveStraight(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.driveSystem.driveStraight(0);
    }
}
